### ISSUE TITLE
Spelling on the SAMBA ( SAMABA instead )

### ISSUE THREAD

**Issue by prashantdv** [CarmineCodes/Make-a-network-drive-on-linux#1]
There is a spelling mistake. I guess it should read as "setup the Samba Docker" but right now it says samaba instead.
![2022-12-13 12_02_51-Window](https://user-images.githubusercontent.com/20724927/207301004-95843116-8662-4f0a-b1b4-f4b057f59abb.png)

**Comment by CarmineCodes** [comment]
thank you for that, just fixed it!
